apiVersion: v1
kind: Pod
spec:
  containers:
    - name: agent
      image: aicacia/build-agent-node:10
      imagePullPolicy: Always
      command:
        - cat
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
