apiVersion: v1
kind: Pod
spec:
  containers:
    - name: agent
      image: aicacia/build-agent-node:10
      imagePullPolicy: Always
      command:
        - cat
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1Gi"
          cpu: 1
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
