apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aicacia-cast-stream-receiver-ui.fullname" . }}-environment
  labels:
    {{- include "aicacia-cast-stream-receiver-ui.labels" . | nindent 4 }}
data:
{{ toYaml .Values.env | indent 2 }}