apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "aicacia-cast-stream-receiver-ui.fullname" . }}
  labels:
    app: {{ include "aicacia-cast-stream-receiver-ui.name" . }}
    chart: {{ include "aicacia-cast-stream-receiver-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "aicacia-cast-stream-receiver-ui.fullname" . }}
  minReplicas: {{ .Values.replicas.min }}
  maxReplicas: {{ .Values.replicas.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.replicas.resource.cpu.utilization }}