apiVersion: v1
kind: Service
metadata:
  name: {{ include "aicacia-cast-stream-receiver-ui.fullname" . }}
  labels:
    {{- include "aicacia-cast-stream-receiver-ui.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aicacia-cast-stream-receiver-ui.selectorLabels" . | nindent 4 }}
