replicas:
  min: 1
  max: 4
  resource:
    cpu:
      utilization: 90

image:
  repository: registry.aicacia.com/ui/cast-stream-receiver-ui
  pullPolicy: Always
  hash: sha256:f191bb18187c583aabdd8519159f6d80ea86eef5f617fbb7f213c420287e31e8

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/secure-backends: "true"
  hosts:
    - host: cast-stream-receiver.aicacia.com
      paths:
        - /
  tls:
    - hosts:
        - cast-stream-receiver.aicacia.com
      secretName: cast-stream-receiver-aicacia-com-crt

resources:
  requests:
    cpu: 15m
    memory: 96Mi
  limits:
    cpu: 30m
    memory: 128Mi
